### ISSUE TITLE
Change pyprojec.toml structure to be tall instead of wide

### ISSUE THREAD

**Issue by SamEdwardes** [SamEdwardes/jupydocs#16]
Current pyproject.toml:

```toml
[tool.jupydocs]
keep-input = [ "README.ipynb", "website/docs/usage_documenting_classes.ipynb", "website/docs/usage_documenting_functions.ipynb", "website/docs/usage_getting_started.ipynb", "website/docs/usage_why_use_jupydocs.ipynb",]
no-input = [ "website/docs/api_reference_numpy_module.ipynb",]
```

It would be easier to read if it was "taller", like poetry dependencies are listed:

```toml
[tool.poetry.dependencies]
python = "^3.7"
ipython = "^7.19.0"
tabulate = "^0.8.7"
rich = "^10.1.0"
typer = "^0.3.2"
toml = "^0.10.2"
```

I should reconfigure so it looks something like this:

```toml
[tool.jupydocs.docs]
README.ipynb = "keep-input"
"website/docs/usage_documenting_classes.ipynb" = "keep-input"
"website/docs/usage_documenting_functions.ipynb" = "keep-input"
"website/docs/usage_getting_started.ipynb" = "keep-input"
"website/docs/usage_why_use_jupydocs.ipynb" = "keep-input"
"website/docs/api_reference_numpy_module.ipynb" = "no-input"
```

This should have no impact on how the user uses the CLI.
